backend:
  name: git-gateway
  branch: main # Rama que quieres usar

media_folder: "img/uploads" # Carpeta para imágenes subidas
public_folder: "/img/uploads" # Ruta pública para las imágenes

collections:
  - name: "productos"
    label: "Productos"
    folder: "_data/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Categoría", name: "categoria", widget: "select", options: ["bolsos", "accesorios", "decoracion"]}
      - {label: "Descripción", name: "descripcion", widget: "text"}
      - {label: "Precio", name: "precio", widget: "number"}
      - {label: "Imagen", name: "imagen", widget: "image"}
      - {label: "Destacado", name: "destacado", widget: "boolean", required: false}
      - {label: "Nuevo", name: "nuevo", widget: "boolean", required: false}
      - {label: "Oferta", name: "oferta", widget: "boolean", required: false}

  - name: "testimonios"
    label: "Testimonios"
    folder: "_data/testimonios"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Ubicación", name: "ubicacion", widget: "string"}
      - {label: "Contenido", name: "contenido", widget: "text"}
      - {label: "Calificación", name: "calificacion", widget: "number", min: 1, max: 5}
      - {label: "Foto", name: "foto", widget: "image", required: false}