backend:
  name: git-gateway
  branch: main

media_folder: "Img"
public_folder: "/Img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "testimonios"
    label: "Testimonios"
    folder: "testimonios"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Ciudad", name: "ciudad", widget: "string" }
      - { label: "Mensaje", name: "mensaje", widget: "text" }
      - { label: "Foto", name: "foto", widget: "image" }
